using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class Pause : MonoBehaviour
{
    bool IsPause;
    public Image pause;

    // Start is called before the first frame update
    void Start()
    {
        IsPause = false;
    }

    // Update is called once per frame
    void Update()
    {
        escDown();
    }

    void escDown()
    {
        if (Input.GetKeyDown(KeyCode.Escape))
        {
            if (!IsPause)   //썞첍 쵖個첇절
            {
                Time.timeScale = 0; //쟺쐑
                pause.gameObject.SetActive(true);   //쟺邦 웒 칙 킨쫚
                IsPause = true;     //썞첍 쟺 킨쫚
                return;
            }
            if (IsPause)   //썞첍 쟺記퍚
            {
                Time.timeScale = 1; //쵖改핌
                pause.gameObject.SetActive(false);   //쟺邦 웒 칙 얳쐑
                IsPause = false;     //썞첍 쵖個 킨쫚
                return;
            }
        }
    }
}
